DROP DATABASE IF EXISTS PYTHON01;
CREATE DATABASE IF NOT EXISTS PYTHON01;
USE PYTHON01;
DROP TABLE IF EXISTS ETUDIANT ;
 CREATE TABLE ETUDIANT (
     numero_ETUDIANT VARCHAR(255) NOT NULL, 
     nom_ETUDIANT VARCHAR(255), 
     prenom_ETUDIANT VARCHAR(255), 
     dateNais_ETUDIANT VARCHAR(255),
     nom_CLASSE VARCHAR(255), 
     PRIMARY KEY (numero_ETUDIANT)) 
     ENGINE=InnoDB; 

DROP TABLE IF EXISTS MATIERE ; 
CREATE TABLE MATIERE (
    nom_MATIERE VARCHAR(255) NOT NULL, 
    PRIMARY KEY (nom_MATIERE)) 
    ENGINE=InnoDB;  
 
DROP TABLE IF EXISTS DEVOIR;     
CREATE TABLE DEVOIR (
    id_DEVOIR INT AUTO_INCREMENT NOT NULL,
    numero_DEVOIR INT, 
    note_DEVOIR FLOAT,
    nom_MATIERE VARCHAR(255), 
    PRIMARY KEY (id_DEVOIR)) 
    ENGINE=InnoDB;       
 

DROP TABLE IF EXISTS CLASSE ; 
CREATE TABLE CLASSE (
    nom_CLASSE VARCHAR(255),  
    PRIMARY KEY (nom_CLASSE)) 
    ENGINE=InnoDB;  
DROP TABLE IF EXISTS FAIRE ; 
CREATE TABLE FAIRE (
    numero_ETUDIANT VARCHAR(255), 
    id_DEVOIR INT, 
    PRIMARY KEY (numero_ETUDIANT,  id_DEVOIR)) 
    ENGINE=InnoDB;  
DROP TABLE IF EXISTS SUIVRE ; 
CREATE TABLE SUIVRE (
    numero_ETUDIANT VARCHAR(255) NOT NULL, 
    nom_MATIERE VARCHAR(255), 
    noteExamen_CONCERNER INT, 
    PRIMARY KEY (numero_ETUDIANT,  nom_MATIERE)) 
    ENGINE=InnoDB;  
-- ALTER TABLE `ETUDIANT` ADD CONSTRAINT FK_CLASSE_nom_CLASSE FOREIGN KEY (nom_CLASSE) REFERENCES `CLASSE` (nom_CLASSE); 
-- ALTER TABLE `DEVOIR` ADD CONSTRAINT FK_MATIERE_nom_MATIERE FOREIGN KEY (nom_MATIERE) REFERENCES MATIERE (nom_MATIERE); 

ALTER TABLE ETUDIANT ADD CONSTRAINT FK_ETUDIANT_nom_CLASSE FOREIGN KEY (nom_CLASSE) REFERENCES CLASSE (nom_CLASSE); 
ALTER TABLE DEVOIR ADD CONSTRAINT FK_DEVOIR_nom_MATIERE FOREIGN KEY (nom_MATIERE) REFERENCES MATIERE (nom_MATIERE); 
ALTER TABLE FAIRE ADD CONSTRAINT FK_FAIRE_numero_ETUDIANT FOREIGN KEY (numero_ETUDIANT) REFERENCES ETUDIANT (numero_ETUDIANT);
 ALTER TABLE FAIRE ADD CONSTRAINT FK_FAIRE_id_DEVOIR FOREIGN KEY (id_DEVOIR) REFERENCES DEVOIR (id_DEVOIR); 
ALTER TABLE SUIVRE ADD CONSTRAINT FK_SUIVRE_numero_ETUDIANT FOREIGN KEY (numero_ETUDIANT) REFERENCES ETUDIANT (numero_ETUDIANT); 
ALTER TABLE SUIVRE ADD CONSTRAINT FK_SUIVRE_nom_MATIERE FOREIGN KEY (nom_MATIERE) REFERENCES MATIERE (nom_MATIERE);